.syntax unified
.cpu cortex-m4
.thumb

@ ═══════════════════════════════════════════════════════════
@ FILE: get_random_byte.s
@ MEMBER: 2 — Entropy & Memory Manager
@ FUNCTION: get_random_byte
@
@ PURPOSE:
@   Returns one cryptographically strong random byte in r0.
@
@   Entropy is gathered from THREE independent physical
@   noise sources on the nRF52833 / micro:bit v2 hardware:
@
@     Source A — Hardware RNG peripheral
@       Uses the on-chip thermal/shot noise from a reverse-
@       biased diode.  With DERCEN=1 (set by init_rng) the
@       bias is corrected by the Von Neumann extractor.
@
@     Source B — On-chip Temperature sensor
@       The TEMP peripheral reads the silicon die temperature
@       in 0.25 °C units.  The low bits of this 32-bit
@       reading contain environmental analog noise that
@       varies with room temperature, board orientation, and
@       nearby heat sources — all impossible for an attacker
@       to predict.
@
@     Source C — Microphone (PDM) data register
@       The micro:bit v2 has a MEMS microphone connected to
@       the PDM peripheral.  Even in a silent room, the mic
@       picks up thermal noise and quantisation jitter.
@       We sample the raw PDM SAMPLE register for its LSBs.
@
@   All three sources are XOR-combined so that even if ONE
@   source has a temporary bias, the other two sources
@   correct the output distribution.
@
@ INPUT:  nothing  (init_rng must have been called first)
@ OUTPUT: r0 = one random byte (0x00–0xFF)
@ CLOBBERS: r0, r1, r2, r3
@ ═══════════════════════════════════════════════════════════

@ ───────────────────────────────────────────────────────────
@ RNG Peripheral Registers  (nRF52833 PS §6.19)
@ ───────────────────────────────────────────────────────────
.equ RNG_VALRDY,        0x4000D100  @ Event: new byte is ready
.equ RNG_VALUE,         0x4000D508  @ The generated random byte

@ ───────────────────────────────────────────────────────────
@ TEMP Peripheral Registers  (nRF52833 PS §6.20)
@ Base: 0x4000C000
@ ───────────────────────────────────────────────────────────
.equ TEMP_START,        0x4000C000  @ Task: start a measurement
.equ TEMP_DATARDY,      0x4000C100  @ Event: result is ready
.equ TEMP_TEMP,         0x4000C508  @ Measured value (0.25°C LSB)

@ ───────────────────────────────────────────────────────────
@ PDM Peripheral Registers  (nRF52833 PS §6.15)
@ Base: 0x40026000
@
@ The micro:bit v2 wires the on-board MEMS mic to the PDM
@ peripheral.  We read the SAMPLE register directly for its
@ low-frequency thermal noise contribution.
@ ───────────────────────────────────────────────────────────
.equ PDM_ENABLE,        0x40026500  @ PDM ENABLE register
.equ PDM_PDMCLKCTRL,    0x40026504  @ Clock divider register
.equ PDM_MODE,          0x40026508  @ Stereo/mono, edge select
.equ PDM_START,         0x40026000  @ Task: start sampling
.equ PDM_SAMPLE,        0x40026060  @ Raw sample register
                                    @ (reflects last PDM data)

@ PDM config values
.equ PDM_ENABLE_VAL,    1           @ ENABLE = 1 → powered on
.equ PDM_CLK_1M,        0x08000000  @ ~1 MHz PDM clock (typical)
.equ PDM_MONO_LEFT,     0x00000001  @ Mono mode, left channel

@ ───────────────────────────────────────────────────────────
.section .text
.global get_random_byte

@ ───────────────────────────────────────────────────────────
@ get_random_byte
@
@ Register map for this function:
@   r0  — scratch / final return value
@   r1  — peripheral register address
@   r2  — read-back value from register
@   r3  — accumulator:  XOR of all entropy sources
@ ───────────────────────────────────────────────────────────
get_random_byte:
    PUSH    {r1, r2, r3, lr}

    @ ════════════════════════════════════════
    @ SOURCE A — Hardware RNG peripheral
    @ ════════════════════════════════════════

    @ Step A-1: Clear the VALRDY event so we wait for a
    @           freshly generated byte, not a stale one.
    LDR     r1, =RNG_VALRDY
    MOV     r2, #0
    STR     r2, [r1]            @ VALRDY = 0 (cleared)

    @ Step A-2: Poll VALRDY until the RNG signals a new byte.
    @           The RNG generates ~16 kbit/s with DERCEN=1.
rng_wait:
    LDR     r1, =RNG_VALRDY
    LDR     r2, [r1]            @ r2 = VALRDY event register
    CMP     r2, #1
    BNE     rng_wait            @ not ready yet → spin

    @ Step A-3: Read the freshly generated byte.
    LDR     r1, =RNG_VALUE
    LDR     r2, [r1]            @ r2 = VALUE (bits [7:0] valid)
    AND     r3, r2, #0xFF       @ r3 = rng_byte  (our accumulator)

    @ Step A-4: Clear VALRDY again so the RNG generates the
    @           next byte while we go read the other sensors.
    LDR     r1, =RNG_VALRDY
    MOV     r2, #0
    STR     r2, [r1]

    @ ════════════════════════════════════════
    @ SOURCE B — On-chip Temperature sensor
    @ ════════════════════════════════════════

    @ Step B-1: Clear DATARDY event.
    LDR     r1, =TEMP_DATARDY
    MOV     r2, #0
    STR     r2, [r1]

    @ Step B-2: Trigger a new temperature measurement.
    LDR     r1, =TEMP_START
    MOV     r2, #1
    STR     r2, [r1]            @ write 1 to START task

    @ Step B-3: Wait for measurement to complete.
    @           Typically takes ~36 µs.
temp_wait:
    LDR     r1, =TEMP_DATARDY
    LDR     r2, [r1]
    CMP     r2, #1
    BNE     temp_wait           @ not done → keep waiting

    @ Step B-4: Read temperature value.
    @   The TEMP register is a signed 32-bit integer in
    @   units of 0.25 °C.  For a room at 25 °C it reads
    @   ~100 (0x64).  We only want the low 8 bits, which
    @   represent sub-degree thermal jitter (noise).
    LDR     r1, =TEMP_TEMP
    LDR     r2, [r1]            @ r2 = temperature raw value
    AND     r2, r2, #0xFF       @ keep only the low byte

    @ Step B-5: XOR into accumulator.
    EOR     r3, r3, r2          @ r3 = rng_byte XOR temp_byte

    @ ════════════════════════════════════════
    @ SOURCE C — Microphone (PDM) noise
    @ ════════════════════════════════════════

    @ Step C-1: Enable the PDM peripheral (idempotent if
    @           it is already running from a previous call).
    LDR     r1, =PDM_ENABLE
    MOV     r2, #PDM_ENABLE_VAL
    STR     r2, [r1]

    @ Step C-2: Configure clock and mono mode.
    LDR     r1, =PDM_PDMCLKCTRL
    LDR     r2, =PDM_CLK_1M
    STR     r2, [r1]

    LDR     r1, =PDM_MODE
    MOV     r2, #PDM_MONO_LEFT
    STR     r2, [r1]

    @ Step C-3: Start PDM sampling.
    LDR     r1, =PDM_START
    MOV     r2, #1
    STR     r2, [r1]

    @ Step C-4: Short busy-wait (~100 cycles) to let the
    @           PDM shift register fill with fresh mic data.
    @           We don't have a timer IRQ here, so we count.
    MOV     r0, #100            @ reuse r0 as loop counter
pdm_settle_loop:
    SUBS    r0, r0, #1
    BNE     pdm_settle_loop

    @ Step C-5: Read the raw PDM sample register.
    @   The SAMPLE register holds the last integrated PDM
    @   data word.  In a quiet environment the value is near
    @   zero, but the LSBs jitter continuously due to
    @   thermal noise from the MEMS capsule.
    LDR     r1, =PDM_SAMPLE
    LDR     r2, [r1]            @ r2 = raw PDM sample
    AND     r2, r2, #0xFF       @ low byte — maximum jitter

    @ Step C-6: XOR into accumulator.
    EOR     r3, r3, r2          @ r3 = rng XOR temp XOR mic

    @ ════════════════════════════════════════
    @ Final result
    @ ════════════════════════════════════════
    @ The accumulator now holds one byte that is the XOR
    @ of three independent physical noise sources.
    @ Even if any single source is biased (e.g., the mic is
    @ silent, or the temperature is stable), the remaining
    @ two sources maintain unpredictability.

    AND     r0, r3, #0xFF       @ r0 = final random byte

    POP     {r1, r2, r3, pc}   @ restore regs and return
