.syntax unified
.cpu cortex-m4
.thumb

@ ═══════════════════════════════════════════════════════════
@ FILE: init_rng.s
@ MEMBER: 2 — Entropy & Memory Manager
@ FUNCTION: init_rng
@
@ PURPOSE:
@   Starts the nRF52833 hardware RNG peripheral with bias
@   correction enabled (DERCEN = 1). Must be called once
@   at boot, BEFORE get_random_byte is ever called.
@
@ INPUT:  nothing
@ OUTPUT: nothing
@ CLOBBERS: r0, r1
@ ═══════════════════════════════════════════════════════════

@ ───────────────────────────────────────────────────────────
@ nRF52833 RNG Peripheral — Memory-Mapped Register Addresses
@ Reference: nRF52833 Product Specification, Section 6.19
@ Base address: 0x4000D000
@ ───────────────────────────────────────────────────────────
.equ RNG_START,     0x4000D000  @ Task: Start the RNG
.equ RNG_STOP,      0x4000D004  @ Task: Stop  the RNG
.equ RNG_VALRDY,    0x4000D100  @ Event: a new byte is ready
.equ RNG_CONFIG,    0x4000D504  @ Config register (DERCEN bit)
.equ RNG_VALUE,     0x4000D508  @ Generated byte lives here

@ CONFIG register bit
.equ RNG_DERCEN,    1           @ Bit 0: Digital Error Reduction
                                @  0 = raw bias, 1 = bias-corrected

@ ───────────────────────────────────────────────────────────
.section .text
.global init_rng

@ ───────────────────────────────────────────────────────────
@ init_rng
@
@ What it does, step by step:
@   1. Stop the RNG cleanly (in case it was already running)
@   2. Enable bias-correction  (DERCEN = 1 in CONFIG)
@   3. Start the RNG peripheral
@
@ After this returns, the RNG is running in the background.
@ Call get_random_byte to harvest a byte whenever you need one.
@ ───────────────────────────────────────────────────────────
init_rng:
    PUSH    {lr}

    @ ── Step 1: Stop the RNG first (clean slate) ──────────
    LDR     r0, =RNG_STOP
    MOV     r1, #1
    STR     r1, [r0]            @ write 1 to STOP task trigger

    @ ── Step 2: Enable bias-correction (DERCEN = 1) ───────
    @ Without DERCEN, the raw hardware has a measurable
    @ statistical bias — some bit values appear more than
    @ others due to transistor asymmetry.  Setting this bit
    @ activates the on-chip Von Neumann corrector so the
    @ output distribution is nearly perfectly uniform before
    @ it even reaches our code.
    LDR     r0, =RNG_CONFIG
    MOV     r1, #RNG_DERCEN
    STR     r1, [r0]            @ CONFIG = 0x00000001

    @ ── Step 3: Start the RNG ──────────────────────────────
    LDR     r0, =RNG_START
    MOV     r1, #1
    STR     r1, [r0]            @ write 1 to START task trigger

    @ RNG is now running in the background.
    @ VALRDY event will fire each time a new byte is ready.

    POP     {pc}
